run-localstack:
	docker-compose up --build -d

stop-localstack:
	docker-compose down --volumes

init:
	terraform init

plan:
	terraform plan

fmt:
	terraform fmt -recursive

validate:
	terraform validate

plan:
	terraform plan

apply:
	terraform apply

destroy:
	terraform destroy
