---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: somerole
spec:
  forProvider:
    assumeRolePolicyDocument: "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Effect\": \"Allow\", \"Action\": [ \"sts:AssumeRole\" ], \"Resource\": \"arn:aws:lambda:us-west-2:000000000000:\" } ] }"
    tags:
      - key: k1
        value: v1
---
apiVersion: lambda.aws.crossplane.io/v1beta1
kind: Function
metadata:
  name: gofunction
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: 'us-east-1'
    packageType: Zip
    code:
      s3Bucket: function-bucket
      s3Key: gofunction-amd64-linux.zip
    roleRef:
      name: somerole
    tags:
      Service: gofunction
