---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: somerole
spec:
  forProvider:
    assumeRolePolicyDocument: "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Effect\": \"Allow\", \"Action\": [ \"sts:AssumeRole\" ], \"Resource\": \"arn:aws:lambda:us-west-2:000000000000:\" } ] }"
    tags:
      - key: k1
        value: v1
---
apiVersion: lambda.aws.crossplane.io/v1beta1
kind: Function
metadata:
  name: gofunction
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: 'us-east-1'
    packageType: Zip
    runtime: go1.x
    handler: gofunction-amd64-linux
    environment:
      variables:
        CLOUD_REGION: 'us-east-1'
        CLOUD_ENDPOINT_URL: 'http://localhost:4566'
    code:
      s3Bucket: function-bucket
      s3Key: gofunction-amd64-linux.zip
    role: 'arn:aws:iam::000000000000:role/somerole'
    tags:
      Service: gofunction
